let all=[
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/cover_19473cce-96ae-4149-aaa1-508f17ac6c28.progressive.jpg?v=1648186636",
        name:"Kimaye Watermelon (1 pc)",
        des:"Watermelon has a sweet,crispy and hydrating flavour. Its texture is mildly granular but its 90% water content makes it a juicy fruit.Its not particularly bright or zesty despite its high Vitamin C content. It has tones of melon similar to that of cucumber's. The sweetest part of the fruit is 'Watermelons heart' which is the centre most part of the fruit.",
        location:"Origin : Maharashtra, India",
        weight:"Weight :1 pc~ (2 kg)",
        price:"₹ 77",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_16c92e1c-a854-4e38-a834-aa33fab78d2d.png?v=1648186449",
        des2:"Bringing to you the Kimaye Watermelon straight from the farms of West Bengal, India. Each Watermelon is traceable to it's farmer and source and meets the Kimaye safety and quality standards.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Health_benefits_887a7d0b-07ef-4650-a7ca-110c23c40be1.png?v=1648186508",
        des3:"Watermelon acts as a coolant, thirst quencher, detoxifier, diuretic, febrifuge. it has anti-inflammatory properties.",


    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/cover.progressive.jpg?v=1647932788",
        name:"Kimaye Green Apples (Pack of 3 pc & 6 pc)",
        des:"Green apples, as their name suggests, have an even, bright green skin, sometimes greenish-yellow. Fruits with a red blush may have been grown in a cooler climate. The Green apple’s white flesh is hard, crispy, and juicy. The flavor of Green apples acidic, but generally refreshing. Green apples grown in South Africa are sweeter than those fruits grown in other parts of the world.",
        location:"Origin : USA, New Zealand",
        weight:"Weight : Pack of 2~(0.3-0.4kg); Pack of 4~(0.7-0.8kg) ",
        price:"₹ 200 - ₹ 390",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_7e6a713a-8e5a-4083-8e68-0771da1d6345.png?v=1647932260",
        des2:"Kimaye partners with best producers around the globe to bring to you superior quality Apples. The stringent quality processes at our facilities ensure that you get nothing but the best.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Health_benefits_c328a1c8-d5d3-4a59-9263-2315376dfe83.png?v=1647932240",
        des3:"Apples are high in vitamin C and dietary fiber, and are also a good source of potassium. The antioxidants and flavonoids in apples help prevent respiratory disease, while the fiber helps with digestion and reduces the risk of developing diabetes. Apples are also low in fat with no cholesterol.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/MangoCover_908c34e6-fcdb-4564-918e-48d7baeaf628.progressive.jpg?v=1645445684",
        name:"Kimaye Alphonso Mangoes",
        des:"Alphonso, the beloved mango variety known for it's matchless aroma and flavour, is often given the epithet The King of Mangoes. Also known as Hapus locally, the variety is a perfect serve for the table.Each Kimaye Alphonso mango is GI tagged, ripened carbide-free, traceable to it's farmer and source and comes with a minimum guaranteed weight and size.",
        location:"Origin : Ratnagiri, India",
        weight:"Weight : 1 pc ~(220g-300g)",
        price:"₹ 300 - ₹ 875",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Mango_promise.png?v=1615008901",
        des2:"Bringing you the GI tagged Alphonso mangoes straight from the farms of Maharashtra. Each mango is organically ripened, traceable to it's farmer and source and comes with a minimum guaranteed weight and size.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Mango.png?v=1615008900",
        des3:"Mangoes are low in calories but full of nutrients. Mango consumption helps in improving vision and minimize the risk of cataract. Mangoes also help in keeping the skin healthy and protects against breast, colon, leukemia and prostate cancer.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/5e8b2ee6-ce8e-42e9-959f-d43c544f586a.png?v=1616326949",
        name:"Kimaye Blueberries (125g)",
        des:"Enjoy the perfect combination of sweet and tart flavor by snacking on the antioxidant rich superfood- Blueberries.",
        location:"Origin : USA, Chile, Europe",
        weight:"Weight : 125g",
        price:"₹ 335",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Kimaye-Promise_d56e9823-cad8-4d8c-8dda-85580dcd52e9-min.png?v=1614750132",
        des2:"Our blueberries deliver the ultimate in consumption experience. These superfruits are packed at the field and air-freighted to get you the freshest and finest blueberries from across the world.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Health-Benefits_056e9d7d-1ce0-4f45-945f-aff2f6c5ec88-min.png?v=1614750131",
        des3:"A super source of antioxidants , blueberries not only prevent carcinogenesis but also reduces the risks of cancer recurrence. They are also known for contributing to eye health and prevent retinal diseases. Consumption of blueberries improves the health of liver and also protects against diabetes, obesity and coronary heart diseases.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/donut-peach-cover.progressive.jpg?v=1647000498",
        name:"Kimaye Peach (Pack of 2 pc & 4 pc)",
        des:"Peaches are round fruits that range in size from 5 to 9 centimeters in diameter. They are distinguished by a downy fuzz covering their thin skins. The fruits mature from green to yellow and then orange with deep red blushing on the side facing the sun. The deep orange flesh is aromatic and juicy and may or may not cling to the hard, almond-shaped central stone. Peaches offer a sweet flavor, balancing sugar and acid for a well-rounded flavor.",
        location:"Origin : South Africa ",
        weight:"Weight : 2 pcs~(0.42) | 4 pcs~(0.84 kg)",
        price:"₹ 597 - ₹ 1,189",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/donut-peach-promise.png?v=1647001437",
        des2:"Kimaye Partners with the best producers around the globe to bring to you the superior quality peaches. The stringent quality processes at our facilities ensure that you get nothing but the best",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/donut-peach-Helath-benefits.png?v=1647001239",
        des3:"Peaches are an excellent source of vitamin A, B-complex vitamins thiamin, riboflavin and niacin, potassium, iron and phosphorus. They are also a good source of fiber, calcium, vitamins C, E, and K.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Avocado.progressive.jpg?v=1622045722",
        name:"Kimaye Avocado Imported (1pc ≈ 250g)",
        des:"Avocado has a rich, buttery and creamy flavor. A great source of healthy fats, Hass Avocados are known to be the most popular variety, mostly grown in coastal valleys of Peru. Avocado can be consumed with salads or can be used to make delicious spreads and dips.",
        location:"Origin : Peru",
        weight:"Pack: 1 pc ≈ 250g",
        price:"₹ 330",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Kimaye-Promise_bb415589-61b2-4756-a3d7-f8684542f9bf-min.png?v=1614752041",
        des2:"Kimaye Parterns with the best producers around the globe to bring to you the superior quality avocados. The stringent quality processes at our facilities ensure that you get nothing but the best!",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/avocado-health-benefits.png?v=1621858748",
        des3:"Avocados are rich in fat (healthy saturated fat) and have high potassium content which helps in reducing the risk of coronary heart diseases. It helps in maintaining muscle function by regulating blood pressure. Avocado is known for their anti-cancer properties. Consumption of avocados strengthens the immune system.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/463b5516-614a-4a66-9556-f4a09e45afbc.png?v=1614326370",
        name:"Kimaye Pear Green (Pack of 2 & 4)",
        des:"Pears are a mildly sweet fruit having a white, grainy, crisp and crunchy flesh.",
        location:"Origin : South Africa",
        weight:"Weight : (Pack of 2)~0.35kg ; (Pack of 4)~0.7kg",
        price:"₹ 128 - ₹ 245",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise.png?v=1599579484",
        des2:"Kimaye partners with best producers around the globe to bring to you the superior quality pears. The stringent quality processes at our facilities ensure that you get nothing but the best!",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health.png?v=1599579483",
        des3:"Pears are a powerhouse of digestive health and prevent constipation. Pears hold the reputation of having low allergenic potential and also help in treatment of allergic diseases like asthma. Pears are known to assist in weight control through their low energy density.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/a0cfceb5-76a4-4994-9d37-978c6dc3b309.png?v=1611811512",
        name:"Kimaye Imported Oranges (Pack of 3 & 6)",
        des:"A low calorie citrus juicy fruit, Oranges are a powerhouse for antioxidants and rich in Vitamin C.",
        location:"Origin : Egypt",
        weight:"(Pack of 3)~ 0.6kg | (Pack of 6)~ 1.2kg",
        price:"₹ 105",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_dd7bf35f-7ed8-47ec-82f2-7893cbd4a2eb.png?v=1599593833",
        des2:"Kimaye partners with best producers around the globe to bring to you the superior quality oranges. The stringent quality processes at our facilities ensure that you get nothing but the best!",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health_ec174997-cfe7-4090-9d2c-2b2df16a1ac0.png?v=1599593833",
        des3:"Oranges are rich in dietary fibre and pectin which reduces blood cholestrol level and fights obesity. Orange consumption leads to a wholesome health and young, fresh and glowing skin. Regular intake of oranges reduce chances of formation of kidney stones.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Nagpuri-santra-cover_dfe991ef-cd37-45a4-94f7-b3225779ab6f.progressive.jpg?v=1634627098",
        name:"Kimaye Nagpuri Santra (2 pc & 4 pc )",
        des:"A variety of Orange from the local farms of Nagpur, Maharashtra (GI Tagged) characterized by unique sweet-sour flavor an aroma that is matchless. The flavor is a result of a unique acid-sugar blend that is not found in any other orange across the world.Each Santra is traceable to its farmer & source and meets the Kimaye safety & quality standards with a minimum guaranteed size and weight.",
        location:"Origin : Maharashtra, India",
        weight:"Weight : 2 pc~(0.4kg to 0.5kg) ; 4 pc ~ (0.8kg to 1kg)",
        price:"₹ 107",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Nagpuri-santra-promise.png?v=1634124808",
        des2:"Coming from the local farms of Nagpur(GI Tagged), each Santra is traceable to its farmer & source. Every piece meets the Kimaye safety and quality standards with a minimum guaranteed size and weight.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Nagpuri-santra--Helath-benefits.png?v=1634124740",
        des3:"Oranges are a rich source of bioflavonoids which are critical for maintaining blood capillary health and also help in treating hemorrhoids, bleeding kidneys and bleeding gums. They keep the immune system strong and ward off winter colds as well as hasten recovery time.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/069bdaa3-eca4-4f4c-8f02-970a626f7be3.png?v=1616393545",
        name:"Kimaye Grapes (Flame Seedless (500g & 2kg)",
        des:"Flame is seedless red grape with medium sized, round berries which have an attractive red colouration, often with some paleness around the stem attachment. The berries are sweet, with a slight hint of sharpness giving a good balance of flavour. Coming from the local farms of Nashik (GI Tagged), each grape is safe to it's core and comes with end-to-end traceability.",
        location:"Origin : Nashik, Maharashtra",
        weight:"500 g2 kg",
        price:"₹ 105",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/flames_1ebaa1ff-f2a3-4a6f-98f1-799ff7130907-min.png?v=1614668560",
        des2:"Coming from the local farms of Nashik (GI Tagged), each grape is safe to it's core and comes with end-to-end traceability. Our farmers follow: Global Good Agricultural Practices(G.A.P) and we test each berry for over 274 pesticide residues in accredited third-party labs. All to ensure that only the best fruits make the cut.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/flames_d5d17eae-5303-4ee9-9479-4c0498dfe90b-min.png?v=1614668559",
        des3:"Red grapes contain higher numbers of antioxidants due to the anthocyanins that also gives them their color. Resveratrol, a key compound in Red Grapes has been shown to increase insulin sensitivity, which may improve body’s ability to use glucose and hence lower blood sugar levels.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/dragon-fruit--white-cover.progressive.jpg?v=1632470660",
        name:"Kimaye Dragon Fruit (1 pc)",
        des:"White Dragon Fruit is a sweet fruit with oval/eclipse shape and white flesh.This fruit has a bright red outer skin that is thick and has prominent scales. Dragon fruit is classified as an exotic cactus fruit and has a succulent inner flesh that is perforated with tiny black seeds similar to that of a kiwi fruit. The flavor of white Dragon fruit is a cross between kiwi, watermelon and cactus pear.",
        location:"Origin : Thailand",
        weight:"Weight :1 pc ≈ 0.40 ~0.45 kg",
        price:"₹ 135",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/dragon-fruit--white-promise.png?v=1632470740",
        des2:"Kimaye partners with best producers around the globe to bring to you the superior quality Dragon Fruit. The stringent quality processes at our facilities ensure that you get nothing but the best.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/AdobeStock_185625459-removebg-preview.png?v=1632484544",
        des3:"White Dragon fruit contains high amounts of vitamin C and high fiber content. They are also a good source of potassium and phosphorus, as well as B-complex vitamins. The fruit is rich in protein and antioxidants . It helps in improving the health of the eyes and skin, including protecting the skin from ultraviolet damage.",
    },
       {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/1_6875ada8-f1e6-4589-b1fd-6f13a86b8ddb-min_540x.jpg?v=1614326164",
        name:"Kimaye Kiwis (3 pcs ≈ 300 g)",
        des:"With fuzzy brown exterior and glistening, bright green flesh, kiwi is juicy and refreshing with a sweet and tarty taste.",
        location:"Origin : New Zealand",
        weight:"Pack : 3 pcs ≈ 0.3 kg",
        price:"₹ 155",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Kimaye-Promise_1a6a5363-3d63-46a6-afe7-7866328a4325-min.png?v=1614687717",
        des2:"Kimaye partners with best producers around the globe to bring to you the superior quality kiwis. The stringent quality processes at our facilities ensure that you get nothing but the best!",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/Health-Benefits_05c6c355-a669-40cf-87d3-ad8de9002d7c-min.png?v=1614687717",
        des3:"The most nutrient dense fruit, Kiwi is known to prevent cancer and cardiovascular diseases. It's consumption helps in reducing effects of depression. It is an immunity booster owing to extremely high vitamin C content and antioxidant compounds.",
    },
       
     {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/24d0f9c9-fe83-40a3-84ab-300e73e4ff8d.png?v=1611811511",
        name:"Coconut Chunks Cup (100g)",
        des:"Kimaye Coconut Chunks are fresh coconut cubes extracted from mature coconuts. A perfect replacement for your on-the-go snack.",
        location:"Origin : India",
        weight:"Pack: 100g",
        price:"₹ 51",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_2ac67997-a3d7-4a9f-b718-218c860e42e2.png?v=1599592042",
        des2:"More hygienic than your house-help! Our ICU like environment, world's most stringent process control and state-of-art packaging ensures that our fresh cut coconuts are produced more hygienically than at your own home.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health_ae018b70-3b94-4338-a147-2c3457eba5fb.png?v=1599592041",
        des3:"Coconut consumption leads to lowering of bad cholestrol level in body. The protein in coconut kernel has potent anti-diabetic activity.",
    },
     {
        img:"",
        name:"",
        des:"",
        location:"",
        weight:"",
        price:"",
        img2:"",
        des2:"",
        img3:"",
        des3:"",
    },
]

let fresh=[
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/24d0f9c9-fe83-40a3-84ab-300e73e4ff8d.png?v=1611811511",
        name:"Coconut Chunks Cup (100g)",
        des:"Kimaye Coconut Chunks are fresh coconut cubes extracted from mature coconuts. A perfect replacement for your on-the-go snack.",
        location:"Origin : India",
        weight:"Pack: 100g",
        price:"₹ 51",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_2ac67997-a3d7-4a9f-b718-218c860e42e2.png?v=1599592042",
        des2:"More hygienic than your house-help! Our ICU like environment, world's most stringent process control and state-of-art packaging ensures that our fresh cut coconuts are produced more hygienically than at your own home.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health_ae018b70-3b94-4338-a147-2c3457eba5fb.png?v=1599592041",
        des3:"Coconut consumption leads to lowering of bad cholestrol level in body. The protein in coconut kernel has potent anti-diabetic activity.",
    },
     {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/47dfb7d1-d8d3-4c96-bda9-7dc85dfdec51.png?v=1613364164",
        name:"Pomegranate Seeds (Arils Cup)125g",
        des:"Kimaye Arils are non-frozen, non-dried, fresh Pomegranate seeds. Pop open the cup to enjoy arils as fresh as a pomegranate opened at your home.",
        location:"Origin : India",
        weight:"OUT OF STOCK",
        price:"₹ 55",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_e56b40c4-fcd0-4814-9371-f6c4b5409d7f.png?v=1599592461",
        des2:"No Preservatives: Our path breaking research led us to the magic of using modified atmospheric packaging. Our arils breathe better to remain fresh longer - all without any chemicals.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health_cc15f9bb-f18b-4e1d-836f-2fb16fb91ff5_2-min.png?v=1614668982",
        des3:"Arils supply iron to blood and hence help to decrease the anemic sysmptoms including fatigue, wooziness and weakness. They help keep the arteries fat free and the heart healthy. They also have anti-microbial properties that fight against bacteria thus helping prevent serious stomach conditions and painful infections.",
    },
     {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/0fce7fd6-f30e-45df-8c52-234acbd62023.png?v=1611811509",
        name:"Grated Coconut Punnet",
        des:"Kimaye freshly grated coconut is as fresh as it could be. Avoid the hassle of grating coconut in your kitchen! You can use this to make chutneys, use for curries or garnishing.",
        location:"Origin : India",
        weight:"Pack: 100g",
        price:"₹ 51",
        img2:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/promise_d5f98ec1-8a94-4eac-a511-d4488e4916f0.png?v=1599592261",
        des2:"Kimaye grated coconut is manufactured in our certified facilites following strict process controls. The technological advancement ensures you'll get the same quality product with Kimaye safety 365 days a year.",
        img3:"https://cdn.shopify.com/s/files/1/0449/5225/6667/files/health_8007e058-14f3-4b6b-b1a4-feccde6ef235.png?v=1599592261",
        des3:"Coconut consumption leads to lowering of bad cholestrol level in body. The protein in coconut kernel has potent anti-diabetic activity.",
    },
     {
        img:"",
        name:"",
        des:"",
        location:"",
        weight:"",
        price:"",
        img2:"",
        des2:"",
        img3:"",
        des3:"",
    },

]

let combo=[
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Grapescombo_1.png?v=1642492575",
        name:"Kimaye Three Grape Combo",
        des:"Curated just for you, Kimaye Grapes Combo is a concoction of three flavours coming from three different colours of grapes. Coming straight from the farms of Nashik, each grape is traceable to it's farmer and source and goes through stringent quality checks by Kimaye before reaching you.  ",
        ul1:"Variety: Grapes Black (Jumbo) (250 g)",
        ul2:"Variety: Super Sonaka Seedless (250 g)",
        ul3:"Variety: Flame Seedless (250 g)",
        price:"₹ 140",
        
    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Untitled.progressive.jpg?v=1617288478",
        name:"Kimaye Flame Seedless-Blueberries Combo",
        des:"Packed with the goodness of antioxidants, Vitamin K and Vitamin C, Kimaye Anti Oxidant Booster is the perfect munchie for your snacking needs. It helps improve eye and skin health and also prevents heart diseases.",
        ul1:"Red Grapes: Flame Seedless (500 g) and",
        ul2:"Blueberries (125 g)",

        price:"₹ 418",
        
    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/GPS-BB.png?v=1642492910",
        name:"Kimaye Blueberry-Green Grapes Combo",
        des:"If you are looking for a nutrient-rich, low-calorie snack, a Blueberry-Grapes combo can never go wrong. A high fibre treat, the fruits do their bit to add to nutrition. While grapes are an excellent source of Vitamin K and potassium, blueberries are an excellent source of Vitamin C with a sweet-tart taste. ",
        ul1:"South American Blueberries (125 g)",
        ul2:"Variety: Super Sonaka Seedless (500 g)",
        price:"₹ 393",
        
    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Grapescombo_540x.png?v=1641883595",
        name:"Kimaye Green & Black Grapes Combo (250 g & 250 g)",
        des:"This two-grape combo is a mix of two of the sweetest grape varieties. Bringing to you the Kimaye grapes straight from the farms of Nashi, each grape is traceable to it's farmer and source and meets the Kimaye safety and quality standards.",
       ul1:"Variety: Jumbo Black Seedless (250 g)",
        ul2:"Variety: Super Sonaka Seedless (250 g)",
        price:"₹ 87",
    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/Wholesome-combo.progressive.jpg?v=1618497683",
        name:"Click to enlarge",
        des:"Just the perfect combination to get you stocked up on the essentials through the week. This wholesome combination is your balanced plate of right taste and nutrition to keep your immunity up and running.",
        ul1:"Bananas (5-6 pcs)",
        ul2:"Kiwis (3 pcs)",
        ul3:"Washington Apples (4 pcs)",
        ul4:"Imported Oranges (6 pcs)",
        ul5:"Green Pear (2 pcs)",
        ul6:"Pomegranate Seeds Arils Cups (4 cups)",
        price:" ₹ 947",
    },
      {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/KiwiBlueberry.png?v=1617983685",
        name:"Kimaye Kiwi-Blueberries Combo",
        des:"Kiwi is a nutrient dense fruit high on Vitamin C and Blueberries is a superfood packed with antioxidants . The Kimaye Kiwi-Blueberry Combo is the perfect combination of sweet and tarty to balance your taste buds. It helps improve immunity, skin health and also helps prevent cancer.",
        ul1:"Kiwis (3pc) and",
        ul2:"Blueberries (125g)",
        price:"₹ 465",
    },
]

let gift=[
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/2I8A7790.progressive.jpg?v=1631346990",
        name:"Fruit Box by Kimaye (Strength)",
        des:"A Fruit box curated specially for you and your loved ones to embrace the strength of the bonds .This Fruit Gift Box by Kimaye consists of the following fruits",
        ul1:"4 pcs of Green Kiwi (0.4 kg)",
        ul2:"4 pcs of Washington Apples (0.7 ~0.8kg)",
        ul3:"4 pcs of Pomegranates (1 kg)",
        ul4:"1 punnet of Blueberries (125 g)",
        ul5:"1 punnet of Red Globe Grapes (400 g)",
        price:"₹ 1,800",
    },
    {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/2I8A7807.progressive.jpg?v=1631347621",
        name:"Fruit Box by Kimaye (Adore)",
        des:"A Fruit box curated specially for you and your loved ones packed with love and colors of fruits. This Fruit Gift Box by Kimaye consists of the following fruits",
        ul1:"4 pcs of Green Kiwi (0.4 kg)",
        ul2:"3 pcs of Washington Apples (0.6 kg)",
        ul3:"3 pcs of Imported Oranges (0.6 kg)",
        ul4:"2 pcs of Pomegranates (0.5 kg)",
        ul5:"1 punnet of Blueberries (125 g)",
        price:"₹ 2,400",


    },
     {
        img:"https://cdn.shopify.com/s/files/1/0449/5225/6667/products/2I8A7821_720x.jpg?v=1631350656",
        name:"Fruit Box by Kimaye (Cherish)",
        des:"A Fruit box curated specially for you and your loved ones filled with all things to cherish and packed with love and health in abundance. This Fruit Gift Box by Kimaye consists of the following fruits",
        ul1:"4 pcs of Washington Apples (0.7 ~0.8 kg)",
        ul2:"4 pcs of Imported Oranges (0.8 kg)",
        ul3:"4 pcs of Pomegranates (0.9 kg)",
        ul4:"2 packs of Pomegranate Seeds (Arils) Cup (125 g)",
        ul5:"1 pack of Arils-Coco Cup (125 g)",
        inst1:"Add recipient/sender name in Gift Instructions in cart.",
        price:"₹ 1,400",


    },
     {
        img:"",
        name:"",
        des:"",
        ul1:"",
        ul2:"",
        ul3:"",
        ul4:"",
        ul5:"",
        price:"",


    },
]
console.log(all);